name: Luca workflow

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: main
  push:
    branches: main
  # schedule:
  #   - cron: "*/15 * * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  say-hello:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: say hello to the world
      run: echo "Hello world!!"
    - name: print current dir path
      run: |
        pwd
        ls -la

  checkout-repo:
    runs-on: ubuntu-latest
    steps:
    - name: checkout with actions
      uses: actions/checkout@v4
    - name: print current dir path after checkout
      run: |
        pwd
        ls -la
    - name: verify java
      run: javac -version; java -version
    # - name: install java
    #   run: sudo apt install -y openjdk-17-jdk openjdk-17-jre
    # - name: verify java
    #   run: javac -version; java -version
    - uses: actions/setup-java@v4
      with:
        java-version: '17'
    - name: verify java
      run: javac -version; java -version
